
import type { HomeWorker } from './types';

export const SERVICE_TYPES = ['Nanny', 'Cook', 'Cleaner'];
export const EXPERIENCE_YEARS = ['0', '1', '2', '3', '4', '5+'];
export const RELIGIONS = ['Orthodox Tewahdo', 'Muslim', 'Protestant', 'Catholic', 'Other'];
export const EDUCATION_LEVELS = ['No Education', 'Primary School', 'Secondary School', 'College Diploma'];
export const LANGUAGES = ['Amharic', 'English', 'Afan Oromo', 'Tigrigna', 'Somali', 'Guragigna', 'Wolayita'];
export const EMPLOYMENT_TYPES = ['Home Based', 'Part-Time'];

export const MOCK_WORKERS: HomeWorker[] = [
  {
    id: 1,
    fullName: 'Abeba Tesfaye',
    age: 28,
    religion: 'Orthodox Tewahdo',
    languages: ['Amharic', 'English'],
    educationLevel: 'Secondary School',
    experience: 3,
    serviceType: 'Nanny',
    phone: '0912345678',
    photoUrl: 'https://picsum.photos/seed/person1/300/300',
    isAvailable: true,
    employmentType: 'Home Based',
  },
  {
    id: 2,
    fullName: 'Fatuma Ahmed',
    age: 35,
    religion: 'Muslim',
    languages: ['Amharic', 'Afan Oromo'],
    educationLevel: 'Primary School',
    experience: 5,
    serviceType: 'Cook',
    phone: '0923456789',
    photoUrl: 'https://picsum.photos/seed/person2/300/300',
    isAvailable: true,
    employmentType: 'Home Based',
  },
  {
    id: 3,
    fullName: 'Sara Berhe',
    age: 22,
    religion: 'Protestant',
    languages: ['Tigrigna', 'English'],
    educationLevel: 'College Diploma',
    experience: 1,
    serviceType: 'Cleaner',
    phone: '0934567890',
    photoUrl: 'https://picsum.photos/seed/person3/300/300',
    isAvailable: false,
    employmentType: 'Part-Time',
  },
  {
    id: 4,
    fullName: 'Lensa Kebede',
    age: 40,
    religion: 'Orthodox Tewahdo',
    languages: ['Afan Oromo', 'Amharic'],
    educationLevel: 'No Education',
    experience: 10,
    serviceType: 'Cook',
    phone: '0945678901',
    photoUrl: 'https://picsum.photos/seed/person4/300/300',
    isAvailable: true,
    employmentType: 'Part-Time',
  },
  {
    id: 5,
    fullName: 'Daniel Yohannes',
    age: 25,
    religion: 'Protestant',
    languages: ['Amharic', 'English', 'Guragigna'],
    educationLevel: 'College Diploma',
    experience: 2,
    serviceType: 'Nanny',
    phone: '0956789012',
    photoUrl: 'https://picsum.photos/seed/person5/300/300',
    isAvailable: true,
    employmentType: 'Home Based',
  },
    {
    id: 6,
    fullName: 'Hana Getachew',
    age: 31,
    religion: 'Orthodox Tewahdo',
    languages: ['Amharic'],
    educationLevel: 'Secondary School',
    experience: 6,
    serviceType: 'Cleaner',
    phone: '0967890123',
    photoUrl: 'https://picsum.photos/seed/person6/300/300',
    isAvailable: false,
    employmentType: 'Home Based',
  },
  {
    id: 7,
    fullName: 'Mohammed Ali',
    age: 45,
    religion: 'Muslim',
    languages: ['Somali', 'Amharic'],
    educationLevel: 'Primary School',
    experience: 15,
    serviceType: 'Cook',
    phone: '0978901234',
    photoUrl: 'https://picsum.photos/seed/person7/300/300',
    isAvailable: true,
    employmentType: 'Part-Time',
  },
  {
    id: 8,
    fullName: 'Tigist Alemu',
    age: 29,
    religion: 'Protestant',
    languages: ['Wolayita', 'Amharic'],
    educationLevel: 'Secondary School',
    experience: 4,
    serviceType: 'Nanny',
    phone: '0989012345',
    photoUrl: 'https://picsum.photos/seed/person8/300/300',
    isAvailable: true,
    employmentType: 'Home Based',
  },
  {
    id: 9,
    fullName: 'Yusuf Ibrahim',
    age: 24,
    religion: 'Muslim',
    languages: ['English', 'Afan Oromo'],
    educationLevel: 'College Diploma',
    experience: 2,
    serviceType: 'Cleaner',
    phone: '0911223344',
    photoUrl: 'https://picsum.photos/seed/person9/300/300',
    isAvailable: true,
    employmentType: 'Part-Time',
  },
  {
    id: 10,
    fullName: 'Martha Solomon',
    age: 33,
    religion: 'Catholic',
    languages: ['Amharic', 'English'],
    educationLevel: 'College Diploma',
    experience: 5,
    serviceType: 'Nanny',
    phone: '0922334455',
    photoUrl: 'https://picsum.photos/seed/person10/300/300',
    isAvailable: false,
    employmentType: 'Home Based',
  },
];
